### ISSUE TITLE
Unique ENC KEY for every tenant db

### ISSUE THREAD

**Issue by UsamaKhan-hub** [ionghitun/laravel-lumen-mysql-encryption#7]
I was wondering as in this package we are setting an encrytion key in .env but lets just take security measures into consideration , as i am have multi tenancy and i want to set unique enc key for each tenant database ? that can be done ? just need some guidance.
Thanks

**Comment by UsamaKhan-hub** [comment]
@ionghitun PLease guide me in this matter, also i am facing a issue if even if i remove ENCRYPTION_KEY variable from .env and after clearing cache on config it or whatever it still logging . where i am using scope, whereEncrypted. i dont know whats going wrong

**Comment by ionghitun** [comment]
Hi, I didn't take in consideration multiple databases, also probably I am going to move this to archive, I will post guidance on how to revert encrypted data, because anyway modern Laravel have extra security measures.

Regarding your second question, is still logging because probably in model the columns are still in encrypted array, the data is encoded with no ENCRYPTION_KEY if that is removed from .env.
